03-challenge-problem-after.py